Repository Virtual-Dynamic-Labs/Virtual-Dynamic-Landing-Page, pull requests merged in 2022-07, with the labels that each got.

#5 Add real links to button.
  src/VirtualDynamicLanding/LandingPage/LandingPageFooter.jsx
  src/VirtualDynamicLanding/LandingPage/LandingPageNavbar.jsx
  src/VirtualDynamicLanding/TeamPage/TeamPageContent.jsx
Labels: bug

#7 Add white paper google doc link to whitepaper page
  src/VirtualDynamicLanding/WhitePaper.jsx
  src/VirtualDynamicLanding/WhitePaper/WhitePaper.jsx
  src/index.js
Labels: enhancement

#9 Issues list Fix redirect problem on netlify bug
  _redirects
Labels: bug

#11 Add netlify.toml to set up redirect
  netlify.toml
Labels: bug

#12 Fix whitepaper height not fit to window size.
  src/VirtualDynamicLanding/WhitePaper/WhitePaper.jsx
Labels: bug

#13 Include the missing footer to team page and white paper page.
  src/VirtualDynamicLanding/TeamPage/TeamPageContent.jsx
  src/VirtualDynamicLanding/WhitePaper/WhitePaper.jsx
Labels: bug

#16 Refactor team introduction page and update background.
  src/VirtualDynamicLanding/TeamPage/TeamPageContent.jsx
Labels: enhancement

#17 Update Role for Team Page
  src/VirtualDynamicLanding/TeamPage/TeamPageContent.jsx
Labels: documentation

#18 Update team info
  src/VirtualDynamicLanding/TeamPage/TeamPageContent.jsx
Labels: bug, documentation

#19 Add a new tab for pitch deck
  src/VirtualDynamicLanding/Deck/Deck.jsx
  src/VirtualDynamicLanding/LandingPage/LandingPageNavbar.jsx
  src/VirtualDynamicLanding/TeamPage/TeamPageContent.jsx
  src/index.js
Labels: documentation, enhancement
